language: node_js
node_js:
- '0.12'
script: env

env:
  global:
    secure: "hxeC/9KKprH/4pgix2/S4L8gs5+elhBYcPTClf7htZPhA05DeKKenuHyG3xO66LMsb5J72YzXOCcYvmKDMpCbAG7LXOf1UiHAfgmp3HFJ7A4pbM18ZCkZmwVqHdtL245ZJa9edLv5ZSEUh9OPeTA6t37njyuSKbQW4l+MM0rN04="
